import { parsePhoneNumberWithError, isValidPhoneNumber, CountryCode } from 'libphonenumber-js';

/**
 * Validate phone number for a specific country
 * @param phoneNumber - The phone number to validate
 * @param countryCode - ISO 3166-1 alpha-2 country code (e.g., 'US', 'GB', 'IN')
 * @returns true if valid, false otherwise
 */
export const validatePhoneNumber = (phoneNumber: string, countryCode: string): boolean => {
  try {
    return isValidPhoneNumber(phoneNumber, countryCode as CountryCode);
  } catch {
    return false;
  }
};

/**
 * Format phone number for a specific country
 * @param phoneNumber - The phone number to format
 * @param countryCode - ISO 3166-1 alpha-2 country code
 * @returns Formatted phone number or original if invalid
 */
export const formatPhoneNumber = (phoneNumber: string, countryCode: string): string => {
  try {
    const parsed = parsePhoneNumberWithError(phoneNumber, countryCode as CountryCode);
    if (parsed) {
      return parsed.formatInternational();
    }
    return phoneNumber;
  } catch {
    return phoneNumber;
  }
};

/**
 * List of countries with their codes and names
 */
export const COUNTRIES = [
  { code: 'AD', name: 'Andorra', flag: 'AD' },
  { code: 'AE', name: 'United Arab Emirates', flag: 'AE' },
  { code: 'AF', name: 'Afghanistan', flag: 'AF' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: 'AG' },
  { code: 'AI', name: 'Anguilla', flag: 'AI' },
  { code: 'AL', name: 'Albania', flag: 'AL' },
  { code: 'AM', name: 'Armenia', flag: 'AM' },
  { code: 'AO', name: 'Angola', flag: 'AO' },
  { code: 'AR', name: 'Argentina', flag: 'AR' },
  { code: 'AS', name: 'American Samoa', flag: 'AS' },
  { code: 'AT', name: 'Austria', flag: 'AT' },
  { code: 'AU', name: 'Australia', flag: 'AU' },
  { code: 'AW', name: 'Aruba', flag: 'AW' },
  { code: 'AZ', name: 'Azerbaijan', flag: 'AZ' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: 'BA' },
  { code: 'BB', name: 'Barbados', flag: 'BB' },
  { code: 'BD', name: 'Bangladesh', flag: 'BD' },
  { code: 'BE', name: 'Belgium', flag: 'BE' },
  { code: 'BF', name: 'Burkina Faso', flag: 'BF' },
  { code: 'BG', name: 'Bulgaria', flag: 'BG' },
  { code: 'BH', name: 'Bahrain', flag: 'BH' },
  { code: 'BI', name: 'Burundi', flag: 'BI' },
  { code: 'BJ', name: 'Benin', flag: 'BJ' },
  { code: 'BL', name: 'Saint Barthélemy', flag: 'BL' },
  { code: 'BM', name: 'Bermuda', flag: 'BM' },
  { code: 'BN', name: 'Brunei', flag: 'BN' },
  { code: 'BO', name: 'Bolivia', flag: 'BO' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', flag: 'BQ' },
  { code: 'BR', name: 'Brazil', flag: 'BR' },
  { code: 'BS', name: 'Bahamas', flag: 'BS' },
  { code: 'BT', name: 'Bhutan', flag: 'BT' },
  { code: 'BW', name: 'Botswana', flag: 'BW' },
  { code: 'BY', name: 'Belarus', flag: 'BY' },
  { code: 'BZ', name: 'Belize', flag: 'BZ' },
  { code: 'CA', name: 'Canada', flag: 'CA' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', flag: 'CC' },
  { code: 'CD', name: 'Congo (Democratic Republic)', flag: 'CD' },
  { code: 'CF', name: 'Central African Republic', flag: 'CF' },
  { code: 'CG', name: 'Congo', flag: 'CG' },
  { code: 'CH', name: 'Switzerland', flag: 'CH' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: 'CI' },
  { code: 'CK', name: 'Cook Islands', flag: 'CK' },
  { code: 'CL', name: 'Chile', flag: 'CL' },
  { code: 'CM', name: 'Cameroon', flag: 'CM' },
  { code: 'CN', name: 'China', flag: 'CN' },
  { code: 'CO', name: 'Colombia', flag: 'CO' },
  { code: 'CR', name: 'Costa Rica', flag: 'CR' },
  { code: 'CU', name: 'Cuba', flag: 'CU' },
  { code: 'CV', name: 'Cape Verde', flag: 'CV' },
  { code: 'CW', name: 'Curaçao', flag: 'CW' },
  { code: 'CX', name: 'Christmas Island', flag: 'CX' },
  { code: 'CY', name: 'Cyprus', flag: 'CY' },
  { code: 'CZ', name: 'Czech Republic', flag: 'CZ' },
  { code: 'DE', name: 'Germany', flag: 'DE' },
  { code: 'DJ', name: 'Djibouti', flag: 'DJ' },
  { code: 'DK', name: 'Denmark', flag: 'DK' },
  { code: 'DM', name: 'Dominica', flag: 'DM' },
  { code: 'DO', name: 'Dominican Republic', flag: 'DO' },
  { code: 'DZ', name: 'Algeria', flag: 'DZ' },
  { code: 'EC', name: 'Ecuador', flag: 'EC' },
  { code: 'EE', name: 'Estonia', flag: 'EE' },
  { code: 'EG', name: 'Egypt', flag: 'EG' },
  { code: 'EH', name: 'Western Sahara', flag: 'EH' },
  { code: 'ER', name: 'Eritrea', flag: 'ER' },
  { code: 'ES', name: 'Spain', flag: 'ES' },
  { code: 'ET', name: 'Ethiopia', flag: 'ET' },
  { code: 'FI', name: 'Finland', flag: 'FI' },
  { code: 'FJ', name: 'Fiji', flag: 'FJ' },
  { code: 'FK', name: 'Falkland Islands', flag: 'FK' },
  { code: 'FM', name: 'Micronesia', flag: 'FM' },
  { code: 'FO', name: 'Faroe Islands', flag: 'FO' },
  { code: 'FR', name: 'France', flag: 'FR' },
  { code: 'GA', name: 'Gabon', flag: 'GA' },
  { code: 'GB', name: 'United Kingdom', flag: 'GB' },
  { code: 'GD', name: 'Grenada', flag: 'GD' },
  { code: 'GE', name: 'Georgia', flag: 'GE' },
  { code: 'GF', name: 'French Guiana', flag: 'GF' },
  { code: 'GG', name: 'Guernsey', flag: 'GG' },
  { code: 'GH', name: 'Ghana', flag: 'GH' },
  { code: 'GI', name: 'Gibraltar', flag: 'GI' },
  { code: 'GL', name: 'Greenland', flag: 'GL' },
  { code: 'GM', name: 'Gambia', flag: 'GM' },
  { code: 'GN', name: 'Guinea', flag: 'GN' },
  { code: 'GP', name: 'Guadeloupe', flag: 'GP' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: 'GQ' },
  { code: 'GR', name: 'Greece', flag: 'GR' },
  { code: 'GS', name: 'South Georgia', flag: 'GS' },
  { code: 'GT', name: 'Guatemala', flag: 'GT' },
  { code: 'GU', name: 'Guam', flag: 'GU' },
  { code: 'GW', name: 'Guinea-Bissau', flag: 'GW' },
  { code: 'GY', name: 'Guyana', flag: 'GY' },
  { code: 'HK', name: 'Hong Kong', flag: 'HK' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', flag: 'HM' },
  { code: 'HN', name: 'Honduras', flag: 'HN' },
  { code: 'HR', name: 'Croatia', flag: 'HR' },
  { code: 'HT', name: 'Haiti', flag: 'HT' },
  { code: 'HU', name: 'Hungary', flag: 'HU' },
  { code: 'ID', name: 'Indonesia', flag: 'ID' },
  { code: 'IE', name: 'Ireland', flag: 'IE' },
  { code: 'IL', name: 'Israel', flag: 'IL' },
  { code: 'IM', name: 'Isle of Man', flag: 'IM' },
  { code: 'IN', name: 'India', flag: 'IN' },
  { code: 'IO', name: 'British Indian Ocean Territory', flag: 'IO' },
  { code: 'IQ', name: 'Iraq', flag: 'IQ' },
  { code: 'IR', name: 'Iran', flag: 'IR' },
  { code: 'IS', name: 'Iceland', flag: 'IS' },
  { code: 'IT', name: 'Italy', flag: 'IT' },
  { code: 'JE', name: 'Jersey', flag: 'JE' },
  { code: 'JM', name: 'Jamaica', flag: 'JM' },
  { code: 'JO', name: 'Jordan', flag: 'JO' },
  { code: 'JP', name: 'Japan', flag: 'JP' },
  { code: 'KE', name: 'Kenya', flag: 'KE' },
  { code: 'KG', name: 'Kyrgyzstan', flag: 'KG' },
  { code: 'KH', name: 'Cambodia', flag: 'KH' },
  { code: 'KI', name: 'Kiribati', flag: 'KI' },
  { code: 'KM', name: 'Comoros', flag: 'KM' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: 'KN' },
  { code: 'KP', name: 'North Korea', flag: 'KP' },
  { code: 'KR', name: 'South Korea', flag: 'KR' },
  { code: 'KW', name: 'Kuwait', flag: 'KW' },
  { code: 'KY', name: 'Cayman Islands', flag: 'KY' },
  { code: 'KZ', name: 'Kazakhstan', flag: 'KZ' },
  { code: 'LA', name: 'Laos', flag: 'LA' },
  { code: 'LB', name: 'Lebanon', flag: 'LB' },
  { code: 'LC', name: 'Saint Lucia', flag: 'LC' },
  { code: 'LI', name: 'Liechtenstein', flag: 'LI' },
  { code: 'LK', name: 'Sri Lanka', flag: 'LK' },
  { code: 'LR', name: 'Liberia', flag: 'LR' },
  { code: 'LS', name: 'Lesotho', flag: 'LS' },
  { code: 'LT', name: 'Lithuania', flag: 'LT' },
  { code: 'LU', name: 'Luxembourg', flag: 'LU' },
  { code: 'LV', name: 'Latvia', flag: 'LV' },
  { code: 'LY', name: 'Libya', flag: 'LY' },
  { code: 'MA', name: 'Morocco', flag: 'MA' },
  { code: 'MC', name: 'Monaco', flag: 'MC' },
  { code: 'MD', name: 'Moldova', flag: 'MD' },
  { code: 'ME', name: 'Montenegro', flag: 'ME' },
  { code: 'MF', name: 'Saint Martin', flag: 'MF' },
  { code: 'MG', name: 'Madagascar', flag: 'MG' },
  { code: 'MH', name: 'Marshall Islands', flag: 'MH' },
  { code: 'MK', name: 'North Macedonia', flag: 'MK' },
  { code: 'ML', name: 'Mali', flag: 'ML' },
  { code: 'MM', name: 'Myanmar', flag: 'MM' },
  { code: 'MN', name: 'Mongolia', flag: 'MN' },
  { code: 'MO', name: 'Macao', flag: 'MO' },
  { code: 'MP', name: 'Northern Mariana Islands', flag: 'MP' },
  { code: 'MQ', name: 'Martinique', flag: 'MQ' },
  { code: 'MR', name: 'Mauritania', flag: 'MR' },
  { code: 'MS', name: 'Montserrat', flag: 'MS' },
  { code: 'MT', name: 'Malta', flag: 'MT' },
  { code: 'MU', name: 'Mauritius', flag: 'MU' },
  { code: 'MV', name: 'Maldives', flag: 'MV' },
  { code: 'MW', name: 'Malawi', flag: 'MW' },
  { code: 'MX', name: 'Mexico', flag: 'MX' },
  { code: 'MY', name: 'Malaysia', flag: 'MY' },
  { code: 'MZ', name: 'Mozambique', flag: 'MZ' },
  { code: 'NA', name: 'Namibia', flag: 'NA' },
  { code: 'NC', name: 'New Caledonia', flag: 'NC' },
  { code: 'NE', name: 'Niger', flag: 'NE' },
  { code: 'NF', name: 'Norfolk Island', flag: 'NF' },
  { code: 'NG', name: 'Nigeria', flag: 'NG' },
  { code: 'NI', name: 'Nicaragua', flag: 'NI' },
  { code: 'NL', name: 'Netherlands', flag: 'NL' },
  { code: 'NO', name: 'Norway', flag: 'NO' },
  { code: 'NP', name: 'Nepal', flag: 'NP' },
  { code: 'NR', name: 'Nauru', flag: 'NR' },
  { code: 'NU', name: 'Niue', flag: 'NU' },
  { code: 'NZ', name: 'New Zealand', flag: 'NZ' },
  { code: 'OM', name: 'Oman', flag: 'OM' },
  { code: 'PA', name: 'Panama', flag: 'PA' },
  { code: 'PE', name: 'Peru', flag: 'PE' },
  { code: 'PF', name: 'French Polynesia', flag: 'PF' },
  { code: 'PG', name: 'Papua New Guinea', flag: 'PG' },
  { code: 'PH', name: 'Philippines', flag: 'PH' },
  { code: 'PK', name: 'Pakistan', flag: 'PK' },
  { code: 'PL', name: 'Poland', flag: 'PL' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', flag: 'PM' },
  { code: 'PN', name: 'Pitcairn Islands', flag: 'PN' },
  { code: 'PR', name: 'Puerto Rico', flag: 'PR' },
  { code: 'PS', name: 'Palestine', flag: 'PS' },
  { code: 'PT', name: 'Portugal', flag: 'PT' },
  { code: 'PW', name: 'Palau', flag: 'PW' },
  { code: 'PY', name: 'Paraguay', flag: 'PY' },
  { code: 'QA', name: 'Qatar', flag: 'QA' },
  { code: 'RE', name: 'Réunion', flag: 'RE' },
  { code: 'RO', name: 'Romania', flag: 'RO' },
  { code: 'RS', name: 'Serbia', flag: 'RS' },
  { code: 'RU', name: 'Russia', flag: 'RU' },
  { code: 'RW', name: 'Rwanda', flag: 'RW' },
  { code: 'SA', name: 'Saudi Arabia', flag: 'SA' },
  { code: 'SB', name: 'Solomon Islands', flag: 'SB' },
  { code: 'SC', name: 'Seychelles', flag: 'SC' },
  { code: 'SD', name: 'Sudan', flag: 'SD' },
  { code: 'SE', name: 'Sweden', flag: 'SE' },
  { code: 'SG', name: 'Singapore', flag: 'SG' },
  { code: 'SH', name: 'Saint Helena', flag: 'SH' },
  { code: 'SI', name: 'Slovenia', flag: 'SI' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', flag: 'SJ' },
  { code: 'SK', name: 'Slovakia', flag: 'SK' },
  { code: 'SL', name: 'Sierra Leone', flag: 'SL' },
  { code: 'SM', name: 'San Marino', flag: 'SM' },
  { code: 'SN', name: 'Senegal', flag: 'SN' },
  { code: 'SO', name: 'Somalia', flag: 'SO' },
  { code: 'SR', name: 'Suriname', flag: 'SR' },
  { code: 'SS', name: 'South Sudan', flag: 'SS' },
  { code: 'ST', name: 'São Tomé and Príncipe', flag: 'ST' },
  { code: 'SV', name: 'El Salvador', flag: 'SV' },
  { code: 'SX', name: 'Sint Maarten', flag: 'SX' },
  { code: 'SY', name: 'Syria', flag: 'SY' },
  { code: 'SZ', name: 'Eswatini', flag: 'SZ' },
  { code: 'TC', name: 'Turks and Caicos Islands', flag: 'TC' },
  { code: 'TD', name: 'Chad', flag: 'TD' },
  { code: 'TF', name: 'French Southern Territories', flag: 'TF' },
  { code: 'TG', name: 'Togo', flag: 'TG' },
  { code: 'TH', name: 'Thailand', flag: 'TH' },
  { code: 'TJ', name: 'Tajikistan', flag: 'TJ' },
  { code: 'TK', name: 'Tokelau', flag: 'TK' },
  { code: 'TL', name: 'Timor-Leste', flag: 'TL' },
  { code: 'TM', name: 'Turkmenistan', flag: 'TM' },
  { code: 'TN', name: 'Tunisia', flag: 'TN' },
  { code: 'TO', name: 'Tonga', flag: 'TO' },
  { code: 'TR', name: 'Turkey', flag: 'TR' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: 'TT' },
  { code: 'TV', name: 'Tuvalu', flag: 'TV' },
  { code: 'TW', name: 'Taiwan', flag: 'TW' },
  { code: 'TZ', name: 'Tanzania', flag: 'TZ' },
  { code: 'UA', name: 'Ukraine', flag: 'UA' },
  { code: 'UG', name: 'Uganda', flag: 'UG' },
  { code: 'UM', name: 'US Minor Outlying Islands', flag: 'UM' },
  { code: 'US', name: 'United States', flag: 'US' },
  { code: 'UY', name: 'Uruguay', flag: 'UY' },
  { code: 'UZ', name: 'Uzbekistan', flag: 'UZ' },
  { code: 'VA', name: 'Vatican City', flag: 'VA' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: 'VC' },
  { code: 'VE', name: 'Venezuela', flag: 'VE' },
  { code: 'VG', name: 'British Virgin Islands', flag: 'VG' },
  { code: 'VI', name: 'US Virgin Islands', flag: 'VI' },
  { code: 'VN', name: 'Vietnam', flag: 'VN' },
  { code: 'VU', name: 'Vanuatu', flag: 'VU' },
  { code: 'WF', name: 'Wallis and Futuna', flag: 'WF' },
  { code: 'WS', name: 'Samoa', flag: 'WS' },
  { code: 'YE', name: 'Yemen', flag: 'YE' },
  { code: 'YT', name: 'Mayotte', flag: 'YT' },
  { code: 'ZA', name: 'South Africa', flag: 'ZA' },
  { code: 'ZM', name: 'Zambia', flag: 'ZM' },
  { code: 'ZW', name: 'Zimbabwe', flag: 'ZW' },
].sort((a, b) => a.name.localeCompare(b.name));
